### ISSUE TITLE
wxStocks_gui TypeError: TopLevelWindow.SetSizeHints(): arguments did not match any overloaded call:

### ISSUE THREAD

**Issue by gwaitsi** [scoofy/wxStocks#7]
Hey Matt. 
Project looks great and i am trying to install on ubuntu 22.10. 
After installing the dependencies from your documentation, I also found I had to install;
- feedparser
- zodb
- fake-useragent

Having done that, after running and setting the password i get;
Startup may take a few moments...
Enter your wxStocks encryption password: 
  ---- wxStocks_db_functions.py|688 ----
Validating your password, this may take a moment...
  ---- wxStocks_db_functions.py|533 ----
attempting to load 0 possible portfolios
  ---- wxStocks_db_functions.py|326 ----
Loading GLOBAL_STOCK_SCREEN_DICT
  ---- wxStocks_db_functions.py|355 ----
Loading SCREEN_NAME_AND_TIME_CREATED_TUPLE_LIST
  ---- wxStocks_gui_position_index.py|24 ----
FINISH THIS TEMPORARY RESTRUCTURING TO WORK CROSSPLATFORM
```
Traceback (most recent call last):
  File "/home/user/python/wxStocks/wxStocks.py", line 85, in <module>
    main()
  File "/home/user/python/wxStocks/wxStocks.py", line 83, in main
    gui.MainFrame().Show()
  File "/home/user/python/wxStocks/wxStocks_modules/wxStocks_gui.py", line 33, in __init__
    self.SetSizeHints(gui_position.MainFrame_SetSizeHints[0],gui_position.MainFrame_SetSizeHints[1])
TypeError: TopLevelWindow.SetSizeHints(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'float'
```
any ideas please?

**Comment by gwaitsi** [comment]
Also, getting this warning SyntaxWarning: "is not" with a literal. Did you mean "!="? at
3990, 3995, 4014, 4029, 4034, 4060

I changed "is not" to "!=" and those warnings disappeared

**Comment by gwaitsi** [comment]
changed line 33 to         self.SetSizeHints(int(gui_position.MainFrame_SetSizeHints[0]),int(gui_position.MainFrame_SetSizeHints[1]))

but got the following error
```
  ---- wxStocks_gui.py|802 ----
YqlScrapePage loaded
Traceback (most recent call last):
  File "/home/user/python/wxStocks/wxStocks.py", line 85, in <module>
    main()
  File "/home/user/python/wxStocks/wxStocks.py", line 83, in main
    gui.MainFrame().Show()
  File "/home/user/python/wxStocks/wxStocks_modules/wxStocks_gui.py", line 48, in __init__
    self.get_data_page = GetDataPage(self.notebook)
  File "/home/user/python/wxStocks/wxStocks_modules/wxStocks_gui.py", line 406, in __init__
    self.spreadsheet_import_page = SpreadsheetImportPage(self.get_data_notebook)
  File "/home/user/python/wxStocks/wxStocks_modules/wxStocks_gui.py", line 973, in __init__
    self.SetSizer(sizer2)
wx._core.wxAssertionError: C++ assertion "CheckExpectedParentIs(w, m_containingWindow)" failed at /tmp/pip-install-lauseale/wxpython_db22c5121e4944cb9533e73242fae8b1/ext/wxWidgets/src/common/sizer.cpp(887) in SetContainingWindow(): Windows managed by the sizer associated with the given window must have this window as parent, otherwise they will not be repositioned correctly.

Please use the window wxPanel@0x556d7c47e910 ("panel") with which this sizer is associated, as the parent when creating the window wxNotebook@0x556d7c51bc00 ("notebook") managed by it.
```

**Comment by scoofy** [comment]
I got bad news. After a serious of updates to multiple underlying libraries, and the obsolete scraping functions, I really think it's dead software for now.

It's definitely fixable, but it's just not something i'm super interested in working on right now. If you want to send me some pull requests, I'm happy to take them, but i looked into it a couple years ago, and something fundamentally changed about how the tabs in wxPython changed, and I couldn't figure it out.
